# Generated by Django 4.2.2 on 2023-06-07 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='username',
        ),
        migrations.AddField(
            model_name='team',
            name='username',
            field=models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='Исключенные пользовател'),
        ),
    ]
