# Generated by Django 4.2.2 on 2023-06-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_app', '0002_remove_team_username_team_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='username',
        ),
        migrations.CreateModel(
            name='ExUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_app.team', verbose_name='Команда')),
                ('username', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Исключенные пользователи')),
            ],
        ),
    ]
